name: firebase_app_distribution_android
description: Android implementation of the firebase_app_distribution plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: firebase_app_distribution
    platforms:
      android:
        package: care.helloprimary
        pluginClass: FirebaseAppDistributionPlugin
        dartPluginClass: FirebaseAppDistributionAndroid

dependencies:
  flutter:
    sdk: flutter
  firebase_app_distribution_platform_interface:
    path: ../firebase_app_distribution_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^6.0.0
