version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/firebase_app_distribution"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/firebase_app_distribution/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/firebase_app_distribution_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/firebase_app_distribution_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/firebase_app_distribution_ios"
    schedule:
      interval: "daily"
