name: _
publish_to: none
environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.20.0"
dev_dependencies:
  melos: ^6.3.3
workspace:
  - firebase_app_distribution
  - firebase_app_distribution_android
  - firebase_app_distribution_ios
  - firebase_app_distribution_platform_interface
