name: firebase_app_distribution_ios
description: iOS implementation of the firebase_app_distribution plugin
version: 1.2.5
homepage: https://github.com/tpucci/firebase_app_distribution
repository: https://github.com/tpucci/firebase_app_distribution

resolution: workspace

environment:
  sdk: ">=3.11.1 <4.0.0"
  flutter: ">=3.41.0"

flutter:
  plugin:
    implements: firebase_app_distribution
    platforms:
      ios:
        pluginClass: FirebaseAppDistributionPlugin
        dartPluginClass: FirebaseAppDistributionIOS

dependencies:
  flutter:
    sdk: flutter
  firebase_app_distribution_platform_interface: 1.2.0
  firebase_core: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ">=6.0.0 <8.0.0"
